<?php
/*
 * Footer of syndicate theme
 */
?>
<!--start footer section-->
<section id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 margin copy">
                <p>&copy; 2012 - <?php echo date('Y') ?> <a href="http://raya-media.com">Raya Media</a>. Powered by Yima</p>
            </div>
            <div class="col-lg-4 col-sm-6 col-offset-2 margin social">
                <a class="facebook" href="<?php echo $this->staticUri('http://www.facebook.com/$usr', 'raya-media'); ?>" target="_blank">Facebook</a> /
                <a class="twitter" href="http://www.twitter.com/awerest" target="_blank">Twitter</a> /
                <a class="google" href="https://plus.google.com/u/0/104533843132286032110/posts" target="_blank">Google+</a> /
                <a class="instagram" href="http://www.instagram.com/awerest" target="_blank">Instagram</a>
            </div>
        </div>
    </div>
</section>

<!-- back to top button -->
<a href="#intro" class="hidden-sm go-top" data-0="opacity: 0;" data-1000="opacity: 1;">Go Top</a>