<?php
/*
 * Footer of syndicate theme
 */
?>
<!--start footer section-->
<section id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 margin copy">
                <p>&copy; 2012 - <?php echo date('Y') ?> <a href="http://raya-media.com">Raya Media</a>. Powered by Yima</p>
            </div>
            <div class="col-lg-4 col-sm-6 col-offset-2 margin social">
                <a class="facebook" href="<?php echo $this->staticUri('http://ir.linkedin.com/in/$usr', 'payamnaderi'); ?>" target="_blank"><i class="icon-linkedin"></i> Linkedin profile</a>
            </div>
        </div>
    </div>
</section>

<!-- back to top button -->
<a href="#intro" class="hidden-sm go-top" data-0="opacity: 0;" data-1000="opacity: 1;">Go Top</a>