<section id="first" class="content">
    <div class="container">
        <div class="row">
            <!--start #1 -->
            <div class="col-lg-6">
                <h1>It's Awesome</h1>
                <p class="lead">With Bootstrap 3, Syndicate is mobile friendly from the start.
                    Instead of adding on optional mobile styles, they're baked right into the core. In fact, Syndicate is mobile first.<br><br>
                    <small>The rset can be a toatl mses and you can sitll raed it wouthit porbelm.
                        Tihs is bcuseae the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe.
                        Awesomeness, true story!</small></p>
            </div>
            <div class="col-lg-6 icons">
                <div class="row">
                    <div class="col-lg-2 col-sm-2">
                        <i class="icon-group" data-bottom-center="font-size: 0px;" data-center-top="font-size: 52px;"></i>
                    </div>
                    <div class="col-lg-10 col-sm-10">
                        <a href="#" class="btn btn-more btn-mini">More</a>
                        <h3>Made for Everyone</h3>
                        <h5>Packed with Features</h5>
                        <p><small>Global CSS settings, fundamental HTML elements styled and enhanced with extensible classes and an advanced grid system.</small></p>
                    </div>
                    <div class="col-lg-2 col-sm-2">
                        <i class="icon-flag" data-bottom-center="font-size: 0px;" data-center-top="font-size: 52px;"></i>
                    </div>
                    <div class="col-lg-10 col-sm-10">
                        <a href="#" class="btn btn-more btn-mini">More</a>
                        <h3>Tons of Components</h3>
                        <h5>Add any, fast and easy</h5>
                        <p><small>Dozens of reusable components built to provide dropdowns, navigation, alerts, popovers and much more.</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>