<?php
$this->headLink(array(
    'rel'   => 'stylesheet',
    'type'  => 'text/css',
    'media' => 'all',
    'id'    => 'rev-google-font',
    'href'  => 'http://fonts.googleapis.com/css?family==Open+Sans:300italic,400italic,600italic,700italic,800italic,300,600,700,800'
   ))
     ->appendStylesheet($this->staticUri('yTheme\theme\builder') . '/rs-plugin/css/responsive.css', 'screen')
     ->appendStylesheet($this->staticUri() . '/rs-plugin/css/settings.css', 'screen')
;

$this->headScript()
    ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js')
    ->appendFile($this->staticUri().'/rs-plugin/js/jquery.themepunch.plugins.min.js')
    ->appendFile($this->staticUri().'/rs-plugin/js/jquery.themepunch.revolution.min.js')
    ->captureStart();

    echo "
    var tpj=jQuery;

                tpj.noConflict();

                var revapi2;

                tpj(document).ready(function() {

                if (tpj.fn.cssOriginal != undefined)
                    tpj.fn.css = tpj.fn.cssOriginal;

                if(tpj('#rev_slider_2_1').revolution == undefined)
                    revslider_showDoubleJqueryError('#rev_slider_2_1');
                else
                   revapi2 = tpj('#rev_slider_2_1').show().revolution(
                    {
                        delay:9000,
                        startwidth:770,
                        startheight:440,
                        hideThumbs:200,

                        thumbWidth:100,
                        thumbHeight:50,
                        thumbAmount:3,

                        navigationType:\"none\",
                        navigationArrows:\"verticalcentered\",
                        navigationStyle:\"navbar\",

                        touchenabled:\"on\",
                        onHoverStop:\"on\",

                        navOffsetHorizontal:0,
                        navOffsetVertical:20,

                        shadow:1,
                        fullWidth:\"on\",

                        stopLoop:\"off\",
                        stopAfterLoops:-1,
                        stopAtSlide:-1,

                        shuffle:\"off\"
                    });

                }); //ready
    ";
    $this->headScript()->captureEnd();
;
?>
<!-- START REVOLUTION SLIDER 2.0.3 -->
<link rel='' id='' href='' type='' media='' />
<div id="rev_slider_2_1_wrapper" class="rev_slider_wrapper banner_container" style="margin:0px auto;background-color:#E9E9E9;padding:0px;margin-top:0px;margin-bottom:0px;max-height:440px;height:440;">
    <div id="rev_slider_2_1" class="rev_slider banner_container" style="display:none;max-height:440px;height:440;">
        <ul>
            <li data-transition="random" data-slotamount="7" data-masterspeed="300" >

                <img src="<?php echo $this->staticUri();?>/images/gallery/Anchor_v1_preview2-880x461.png" >

                <div class="tp-caption big_white fade"
                     data-x="550"
                     data-y="90"
                     data-speed="300"
                     data-start="500"
                     data-easing="easeOutExpo">
                    <div><?php echo $this->passed_variable; ?></div>
                </div>


                <div class="tp-caption very_large_text fade"
                     data-x="224"
                     data-y="24"
                     data-speed="300"
                     data-start="500"
                     data-easing="easeOutExpo">
                    <div>Widgetized render.</div>
                </div>
            </li>

            <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                <img src="<?php echo $this->staticUri('yTheme\theme\builder');?>/images/gallery/1.jpg" >

                <div class="tp-caption fade"
                     data-x="41"
                     data-y="28"
                     data-speed="300"
                     data-start="800"
                     data-easing="easeOutExpo">
                    <img src="<?php echo $this->staticUri('yTheme\theme\builder');?>/images/gallery/ipad1.png" alt="Image 1"></div>

                <div class="tp-caption fade"
                     data-x="256"
                     data-y="90"
                     data-speed="300"
                     data-start="1100"
                     data-easing="easeOutExpo">
                    <img src="<?php echo $this->staticUri('yTheme\theme\builder');?>/images/gallery/ipad21.png" alt="Image 3"></div>
            </li>

        </ul>
    </div>
</div>
<!-- END REVOLUTION SLIDER -->