<!--start intro section-->
<section id="intro">
    <div id="carousel_intro" class="carousel slide fadeing">
        <div class="carousel-inner">
            <div class="active item" id="slide_3" data-start="background-position: center 0px;" data-1440="background-position: center -250px;">
                <h1 data-start="opacity:1; top: 45%;" data-250="opacity: 0; top: 10%;"><?php echo $words; ?></h1>
            </div>
        </div>
        <button class="left carousel-control" href="#carousel_intro" data-slide="prev" data-start="opacity: 0.6; left: 0%;" data-250="opacity:0; left: 5%;"><i class="icon-chevron-left"></i></button>
        <button class="right carousel-control" href="#carousel_intro" data-slide="next" data-start="opacity: 0.6; right: 0%;" data-250="opacity:0; right: 5%;"><i class="icon-chevron-right"></i></button>
    </div>
    <?php if ($have_more) { ?>
    <div class="hidden-sm more">
        <a href="#first" class="btn btn-cool squared" data-start="opacity:1; margin-top: 0%;" data-150="opacity:0; margin-top: -10%;"><i class="icon-angle-down"></i> See more</a>
    </div>
    <?php } ?>
</section>
<!--end intro section-->