<div class="row">
<div class="span12">
<div class="row">
    <div class="span4 hidden-phone column_container">
        <div class="row-fluid">
            <div class="span12">

                <div style="background-color: rgb(58, 58, 58); padding: 10px; margin-bottom: 20px;">
                    <h1 style="color: rgb(255, 255, 255) !important; margin-bottom: 3px !important;"><b><?php echo $this->translate('WELCOME')?> !</b></h1>
                    <h5 style="color: rgb(255, 255, 255);"><?php echo $this->translate('A better rapid way to develop web applications.')?></h5>
                </div>

                <p>
                    <?php echo $this->translate('What do you need - blogging portal, content management system, CRM system, gallery application or even personal social network site?')?>
                    <br/>
                    <?php echo $this->translate('This is An application framework which binds all the modules into one web application.')?>
                </p>

                <hr class="visible-desktop"></hr>
                <h4 class="visible-desktop"><?php echo $this->translate('Some of Features')?> :</h4>

                <div class="visible-desktop">
                    <div class="span6">
                        <ul class="unstyled" style="margin-top: 10px;">
                            <li><em class="icon-user"></em> Based on ZendFramework 2 </li>
                            <li><em class="icon-th"></em> Easy to Extend </li>
               '/rs-plugin/js/jquery.themepunch.revolution.min.js'             <li><em class="icon-resize-horizontal"></em> Plug & Play module installation </li>
                        </ul>
                    </div>

                    <div class="span6">
                        <ul class="unstyled" style="margin-top: 10px;">
                            <li><em class="icon-resize-small"></em> Service Oriented Design </li>
                            <li><em class="icon-eye-open"></em> Well Documented </li>
                            <li><em class="icon-list-alt"></em> Common web application configuration sets </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="span8 mrgbtm35">
        <div id="banner_container">
            <?php
                // widget like template things.
                echo $this->render('self-plugins/revolutionSlider', array('passed_variable'=>'Passed variable.'));
            ?>
        </div>
    </div>

</div>

<!-- Divider -->
<div class="row">
    <div class="span12">
        <div class="home_separator"></div>
    </div>
</div>

<div class="row mrgbtm35">
    <div class="span4">
        <div style="background-color: rgb(241, 241, 241); padding: 15px; background-position: initial initial; background-repeat: initial initial;">
            <p style="text-align: center;">
                <img class="size-full aligncenter" title="round1" src="<?php echo $this->staticUri('yTheme\theme\builder');?>/images/admin.png" alt="" width="50" height="50"/>
            </p>
            <h4 style="text-align: center;">Powerful Admin Panel</h4>
            <p style="text-align: center; font-size: 11px; margin-bottom: 0px !important;">We have built a custom options panel with more then 300 options, that let's you customize your theme any way you want to!</p>
        </div>
    </div>
    <div class="span4">
        <div style="background-color: rgb(241, 241, 241); padding: 15px; background-position: initial initial; background-repeat: initial initial;">
            <p style="text-align: center;">
                <img class="size-full aligncenter" title="round1" src="<?php echo $this->staticUri('yTheme\theme\builder');?>/images/frame.png" alt="" width="50" height="50"/>
            </p>
            <h4 style="text-align: center;">Imagine & Create</h4>
            <p style="text-align: center; font-size: 11px; margin-bottom: 0px !important;">Now you'll be able to create complex layouts within minutes! It's build on top of the Twitter Bootstrap and jQuery UI frameworks!</p>
        </div>
    </div>
    <div class="span4">
        <div style="background-color: rgb(241, 241, 241); padding: 15px; background-position: initial initial; background-repeat: initial initial;">
            <p style="text-align: center;">
                <img class="size-full wp-image-1095 aligncenter" title="round1" src="<?php echo $this->staticUri('yTheme\theme\builder');?>/images/ipad.png" alt="" width="50" height="50"/>
            </p>
            <h4 style="text-align: center;">Responsive Design</h4>
            <p style="text-align: center; font-size: 11px; margin-bottom: 0px !important;">Responsive designs that addapts to smaller devices. Also Builder Theme have 4 loayouts: 2 Boxed and 2 Fullwidth!</p>
        </div>
    </div>
</div>


</div>
</div>