<?php echo $this->doctype(); ?>
<html dir="ltr" lang="en-US">
<head>
    <meta charset="utf-8">

    <?php echo $this->headTitle('RAYA media '. $this->translate('Application Framework'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        // <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        // <meta http-equiv="X-UA-Compatible" content="IE=edge">
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php
    // set static server
    $this->staticServer('cThemes\theme\builder');

    echo $this->headLink(
            array(
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->staticServer() . '/img/favicon.ico'
            )
        )
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C700italic%2C800italic%2C400%2C300%2C600%2C700%2C800&amp;subset=latin%2Ccyrillic-ext%2Cgreek-ext%2Cgreek%2Cvietnamese%2Clatin-ext%2Ccyrillic&amp;ver=3.4.2')

        ->prependStylesheet($this->staticServer('/css/full_width_1170.css') )
        ->prependStylesheet($this->staticServer('/css/builder.css') )
        ->prependStylesheet($this->staticServer('/css/options.css') )                 #  ^
        ->prependStylesheet($this->staticServer('/css/docs.css') )                    # / \
        ->prependStylesheet($this->staticServer('/css/wide_layout.css') )             # ||
        ->prependStylesheet($this->staticServer() . '/css/bootstrap-responsive.css')  # ||
        ->prependStylesheet($this->staticServer() . '/css/bootstrap.css')             # ||

        ->appendStylesheet($this->staticServer() . '/css/ie.css', 'screen', 'lte IE 8')
    ;
    ?>

    <?php echo $this->headScript()
        ->prependFile($this->staticServer('/js/bootstrap.min.js'))

        ->appendFile('http://html5shim.googlecode.com/svn/trunk/html5.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>
<body>
<div class="wide_cont">

    <?php echo $this->render('inc_tophead');?>

    <!--MAIN CONTENT AREA-->
    <div class="main_content_area">
        <div class="container">
            <?php $this->staticServer(false); //reset to basePath()?>
            <?php echo $this->content; ?>
        </div>
    </div>
    <!--END MAIN CONTENT AREA-->

    <?php echo $this->render('inc_footer');?>

</body>

</html>