<div class="twitter-block">
</div>

<!--FOOTER-->
<!--START BOTTOM LINE-->
<div class="bottom_line">
    <div class="container">
        <div class="row">
            <!-- START COPYRIGHT INFORMATION-->
            <div class="span6">
                <span class="copyright">&copy; 2012 - <?php echo date('Y') ?> by Raya Media. <?php echo $this->translate('All rights reserved.') ?></span>
            </div>
            <!-- END COPYRIGHT INFORMATION-->
            <div class="span6">
                <!-- START FOOTER MENU-->
                <!--
                <span class="copyright pull-right visible-desktop">
                    <div class="menu-footer-menu-container">
                        <ul class="unstyled footer_menu" id="menu-footer-menu">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="about.html">About Us</a></li>
                            <li><a href="big-image-right-sidebar.html">Blog</a></li>
                            <li><a href="2-columns-portfolio.html">Portfolio</a></li>
                            <li><a href="contacts.html">Contacts</a></li>
                        </ul>
                    </div>
                </span>
                -->
                <!-- END FOOTER MENU-->
            </div>
        </div>
    </div>
</div>
<!--END BOTTOM LINE-->
<!--END FOOTER-->
<?php echo $this->inlineScript(); ?>